name: "CI"

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

env:
  FORCE_COLOR: 1

jobs:
  eval:
    name: Evaluate
    runs-on: ubuntu-latest
    outputs:
      stdout: ${{ steps.nix-eval-jobs.outputs.stdout }}
    steps:
      - uses: actions/checkout@v7
      - uses: samueldr/lix-gha-installer-action@v2026-06-15
      - uses: Mic92/hestia@v2
        with:
          upstream-cache-filter: true
      - name: Run nix-eval-jobs
        id: nix-eval-jobs
        run: |
          {
            echo 'stdout<<EOF'
            nix-shell nix/ci-shell.nix --run eval-checks
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

  build:
    needs: [ eval ]
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        derivation: ${{ fromJson(needs.eval.outputs.stdout) }}
    steps:
      - uses: actions/checkout@v7
        if: ${{ ! matrix.derivation.isCached }}
      - uses: samueldr/lix-gha-installer-action@v2026-06-15
        if: ${{ ! matrix.derivation.isCached }}
      - uses: Mic92/hestia@v2
        if: ${{ ! matrix.derivation.isCached }}
        with:
          upstream-cache-filter: true
      - name: Build ${{ matrix.derivation.attr }}
        if: ${{ ! matrix.derivation.isCached }}
        run: nix-build release.nix -A ${{ matrix.derivation.attr }}

  # Only here for branch protection rules
  build-status:
    needs: [ build ]
    name: Build Status
    runs-on: ubuntu-latest
    if: always()
    steps:
    - run: ${{!contains(needs.build.result, 'failure')}}
